monitor=,preferred,auto,auto
# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = waybar & hyprpaper & nm-applet --indicator
# exec-once = ags & hyprpaper & nm-applet --indicator

# GENERAL
source = modules/general.conf
source = modules/animations.conf
source = modules/cursors.conf

## INPUTS
source = modules/inputs.conf

## KEYBINDS
source = modules/workspaces.conf
source = modules/windows.conf
source = modules/programs.conf
source = modules/controls.conf

## RULES
source = modules/rules.conf

# Some default env vars.
env = XCURSOR_SIZE,16
env = QT_QPA_PLATFORMTHEME,qt6ct # change to qt6ct if you have that
