$mainMod = SUPER
binde =, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+
binde =, XF86AudioLowerVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%-
bind =, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind =, XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

binde=,XF86MonBrightnessDown,exec,brightnessctl set 5%-
binde=,XF86MonBrightnessUp,exec,brightnessctl set +5%

bind = ,XF86AudioPlay, exec, playerctl play-pause
bind = ,XF86AudioPrev, exec, playerctl previous
bind = ,XF86AudioNext, exec, playerctl next

# bind = $mainMod SHIFT, S, exec, grim -l 9 -g "$(slurp)" - | swappy -f -
bind = $mainMod SHIFT, S, exec, grim -l 9 -g "$(slurp)" ~/Pictures/ScreenShots/$(date +'%Y-%m-%d_%H-%M-%S')" "ScreenShot | wl-copy
bind = ,Print, exec, grim -l 9 ~/Pictures/ScreenShots/$(date +'%Y-%m-%d&%H-%M-%S')" "ScreenShot | wl-copy
# bind = $mainMod SHIFT, R, exec, wf-recorder -g "$(slurp)" --audio -f $(date +'%Y-%m-%d&%H-%M-%S_Record.mp4')

# bind = Space&Shift_L&Alt_L, Ctrl_L&Super_L, exec, emote # Don't Work
