input {
  kb_layout = latam
  kb_variant = deadtilde
  kb_model = pc104x
  kb_options =
  kb_rules =

  follow_mouse = 1

  touchpad {
    disable_while_typing = false
    natural_scroll = no
#    middle_button_emulation = true # If press LCLICK & RCLICK send MCLICK


  }
  
  sensitivity = 0 # -1.0 to 1.0, 0 means no modification
  
}

