$mainMod = SUPER

$fileManager = nautilus
$browser = microsoft-edge
$terminal = kitty
$menu = wofi
$player = spotify
$discord = vesktop
$bar = waybar

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, W, exec, pkill $bar || $bar
bind = $mainMod, R, exec, pkill $menu || $menu
bind = $mainMod, B, exec, $browser
bind = $mainMod, M, exec, $player
bind = $mainMod, D, exec, $discord

bind = $mainMod, F, fullscreen,
bind = $mainMod, C, killactive,
