$mainMod = SUPER

$fileManager = nautilus
$browser = microsoft-edge
$terminal = kitty
$menu = rofi -show drun -show-icons
$player = spotify
$discord = vesktop

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, E, exec, $fileManager 
bind = $mainMod, R, exec, $menu
bind = $mainMod, B, exec, $browser
bind = $mainMod, M, exec, $player
bind = $mainMod, D, exec, $discord

bind = $mainMod, F, fullscreen,
bind = $mainMod, C, killactive,
