# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

windowrulev2 = float, class:($calculator)

windowrulev2 = float, class:($notes)
windowrulev2 = pin, class:($notes)
windowrulev2 = size 256 348, class:($notes) # 348 512

windowrulev2 = float, class:($sound)

windowrulev2 = float, class:($bluetooth)

workspace = 1, bordersize:2, gapsin:4, gapsout:12 # TEST


# Change Layout
bind = $mod CTRL, D, exec, hyprctl keyword general:layout dwindle
bind = $mod CTRL, M, exec, hyprctl keyword general:layout master

