# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

windowrulev2 = float, title:(Calculadora)

windowrulev2 = float, title:(Iotas)
windowrulev2 = pin, title:(Iotas)
windowrulev2 = size 384 512, title:(Iotas)

windowrulev2 = float, title:(myxer)

workspace = 1, bordersize:2, gapsin:4, gapsout:12
