# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

windowrulev2 = float, class:(org.gnome.Calculator)

windowrulev2 = float, class:(org.gnome.World.Iotas)
windowrulev2 = pin, class:(org.gnome.World.Iotas)
windowrulev2 = size 384 512, class:(org.gnome.World.Iotas)

windowrulev2 = float, class:(myxer)

windowrulev2 = float, class:(.blueman-manager-wrapped)
windowrulev2 = size 384 384, class:(.blueman-manager-wrapped)

workspace = 1, bordersize:2, gapsin:4, gapsout:12
