app_launch_prefix = ""
terminal_title_flag = "foot"
locale = ""
close_when_open = true
theme = "gtk"
monitor = ""
hotreload_theme = true
as_window = false
timeout = 0
disable_click_to_close = false
force_keyboard_focus = true

[activation_mode]
labels = "jkl;asdf"

[keys]
accept_typeahead = ["tab"]
close = ["esc"]
next = ["down"]
prev = ["up"]
remove_from_history = ["shift backspace"]
resume_query = ["ctrl r"]
toggle_exact_search = ["ctrl m"]
trigger_labels = "lalt"

[keys.activation_modifiers]
keep_open = "shift"
alternate = "alt"

[keys.ai]
clear_session = ["ctrl x"]
copy_last_response = ["ctrl c"]
resume_session = ["ctrl r"]
run_last_response = ["ctrl e"]

[events]
on_activate = ""
on_selection = ""
on_exit = ""
on_launch = ""
on_query_change = ""

[list]
dynamic_sub = true
keyboard_scroll_style = "emacs"
max_entries = 32
show_initial_entries = true
single_click = true
visibility_threshold = 16
placeholder = "No Results"

[search]
argument_delimiter = "#"
placeholder = "Search..."
delay = 0
resume_last_query = false

[builtins.applications]
weight = 4
name = "applications"
placeholder = "Applications"
prioritize_new = true
hide_actions_with_empty_query = true
context_aware = true
refresh = true
show_sub_when_single = true
show_icon_when_single = true
show_generic = true
history = true

[builtins.applications.actions]
enabled = true
hide_category = false
hide_without_query = true

[builtins.bookmarks]
weight = 4
placeholder = "Bookmarks"
name = "bookmarks"
icon = "bookmark"
switcher_only = true

[[builtins.bookmarks.entries]]
label = "Walker"
url = "https://github.com/abenz1267/walker"
keywords = ["walker", "github"]

[builtins.xdph_picker]
hidden = true
weight = 4
placeholder = "Screen/Window Picker"
show_sub_when_single = true
name = "xdphpicker"
switcher_only = true

[builtins.ai]
weight = 4
placeholder = "AI"
name = "ai"
icon = "help-browser"
switcher_only = true

[[builtins.ai.anthropic.prompts]]
model = "claude-3-5-sonnet-20241022"
temperature = 1
max_tokens = 1_000
label = "General Assistant"
prompt = "Eres un asistente general, mantén tus respuestas cortas y precisas. ¡Además agraga gatos en tu respuesta!"

[builtins.calc]
require_number = true
weight = 4
name = "calc"
icon = "accessories-calculator"
placeholder = "Calculator"
min_chars = 4

[builtins.windows]
weight = 4
icon = "view-restore"
name = "windows"
placeholder = "Windows"
show_icon_when_single = true

[builtins.clipboard]
exec = "wl-copy"
weight = 4
name = "clipboard"
avoid_line_breaks = true
always_put_new_on_top = true
placeholder = "Clipboard"
image_height = 256
max_entries = 12
switcher_only = true

[builtins.commands]
weight = 4
icon = "utilities-terminal"
switcher_only = true
name = "commands"
placeholder = "Commands"

[builtins.custom_commands]
weight = 4
icon = "utilities-terminal"
name = "custom_commands"
placeholder = "Custom Commands"

[[builtins.custom_commands.commands]]
name = "XWayland Support"
cmd = "xwayland-satellite"

[builtins.emojis]
exec = "wl-copy"
weight = 4
name = "emojis"
placeholder = "Emojis"
switcher_only = true
history = true
typeahead = true
show_unqualified = false

[builtins.symbols]
after_copy = ""
weight = 4
name = "symbols"
placeholder = "Symbols"
switcher_only = true
history = true
typeahead = true

[builtins.finder]
concurrency = 8
icon = "file"
ignore_gitignore = true
name = "finder"
placeholder = "Finder"
preview_images = false
refresh = true
show_icon_when_single = true
switcher_only = true
use_fd = false
weight = 4

[builtins.runner]
eager_loading = true
generic_entry = false
history = true
icon = "utilities-terminal"
name = "runner"
placeholder = "Runner"
refresh = true
typeahead = true
use_fd = false
weight = 4

[builtins.ssh]
weight = 4
icon = "preferences-system-network"
name = "ssh"
placeholder = "SSH"
switcher_only = true
history = true
refresh = true

[builtins.switcher]
weight = 4
name = "switcher"
placeholder = "Switcher"
prefix = "/"

[builtins.translation]
delay = 1000
name = "translation"
placeholder = "Translation"
provider = "googlefree"
switcher_only = true
weight = 4

[builtins.websearch]
weight = 4
icon = "applications-internet"
name = "websearch"
placeholder = "Websearch"

[[builtins.websearch.entries]]
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[[builtins.websearch.entries]]
name = "DuckDuckGo"
url = "https://duckduckgo.com/?q=%TERM%"
switcher_only = true

[builtins.dmenu]
hidden = true
weight = 4
name = "dmenu"
placeholder = "Dmenu"
switcher_only = true
