[ui.window.box]
max_height = 256
min_width = 512
height = 256
width = 512

[ui.window.box.bar]
orientation = "horizontal"
position = "end"

[ui.window.box.bar.entry.icon]
pixel_size = 32
theme = "Stylish-Adwaita"

[ui.window.box.ai_scroll]
name = "aiScroll"

[ui.window.box.ai_scroll.list]
name = "aiList"
orientation = "vertical"

[ui.window.box.ai_scroll.list.item]
name = "aiItem"
wrap = true

[ui.window.box.scroll.list]
max_height = 256
min_width = 512
height = 256
width = 512

[ui.window.box.search.prompt]
name = "prompt"
icon = "edit-find"
theme = "Stylish-Adwaita"
pixel_size = 16

[ui.window.box.search.clear]
name = "clear"
icon = "edit-clear"
theme = "Stylish-Adwaita"
pixel_size = 16

[ui.window.box.search.input]
icons = true

[ui.window.box.search.spinner]
hide = false
