name: Update Flake

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 2,5'

permissions:
  contents: write
  pull-requests: write
  checks: write
  id-token: write

jobs:
  lockfile:
    name: Lockfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v24
        id: update
        with:
          commit-msg: "chore(flake): update inputs"
          pr-title: "chore(flake): update inputs"
          pr-labels: |
            dependencies
            automated
          pr-body: |
            Automated flake update.
            
            ```
            ${{ env.GIT_COMMIT_MESSAGE }}
            ```

      - name: Check the Flake
        if: steps.update.outputs.pull-request-operation == 'created'
        id: check
        run: nix flake check

      - name: Update Check Status
        uses: LouisBrunner/checks-action@v2.0.0
        if: always() && steps.update.outputs.pull-request-operation == 'created'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Update Flake Status
          conclusion: ${{ job.status }}
          sha: ${{ steps.update.outputs.pull-request-head-sha }}

      - name: Auto-Merge or Close
        if: steps.update.outputs.pull-request-operation == 'created'
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ steps.update.outputs.pull-request-number }}
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            gh pr merge $PR_NUMBER --rebase --auto
          else
            gh pr close $PR_NUMBER --comment "Auto-closing: Flake check failed. Check logs." --delete-branch
          fi
